INSERT INTO users(phone,last_name,first_name,address,email, password, enabled, reservation_access) VALUES ('997-444-333','Kowalski','Jan','Warszawa, Solna 44','admin@gmail.com','$2a$10$80Yl05wyCrYpPsSL6lfKk.Gj5W1gTKauzU4vwXMuTD3qOPXHjTXg2', 1, 1);
INSERT INTO authorities(email, authority) VALUES ('admin@gmail.com','ROLE_ADMIN');
INSERT INTO courts(id,name) VALUES (1,'kort 1');
INSERT INTO courts(id,name) VALUES (2,'kort 2');
INSERT INTO courts(id,name) VALUES (3,'kort 3');
INSERT INTO hours(id,name) VALUES (1,'8:00');
INSERT INTO hours(id,name) VALUES (2,'8:30');
INSERT INTO hours(id,name) VALUES (3,'9:00');
INSERT INTO hours(id,name) VALUES (4,'9:30');
INSERT INTO hours(id,name) VALUES (5,'10:00');
INSERT INTO hours(id,name) VALUES (6,'10:30');
INSERT INTO hours(id,name) VALUES (7,'11:00');
INSERT INTO hours(id,name) VALUES (8,'11:30');
INSERT INTO hours(id,name) VALUES (9,'12:00');
INSERT INTO hours(id,name) VALUES (10,'12:30');
INSERT INTO hours(id,name) VALUES (11,'13:00');
INSERT INTO hours(id,name) VALUES (12,'13:30');
INSERT INTO hours(id,name) VALUES (13,'14:00');
INSERT INTO hours(id,name) VALUES (14,'14:30');
INSERT INTO hours(id,name) VALUES (15,'15:00');
INSERT INTO hours(id,name) VALUES (16,'15:30');
INSERT INTO hours(id,name) VALUES (17,'16:00');